<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>avatar</AssemblyName>
    <RootNamespace>AvatarLauncher</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
