[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "avatar_pomodoro"
version = "0.1.1"
description = "Pomodoro timer plugin for the avatar project"

authors = [
    { name = "Angelovich", email = "angel777da@gmail.com" },
]

requires-python = ">=3.13"
dependencies = [
    "avatar.api >= 0.1.0",
    "avatar.ui >= 0.1.0",
]

license = "MIT"

[project.entry-points.'avatar.plugins']
avatar_pomodoro = 'avatar_pomodoro'

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
avatar_pomodoro = ["*.html"]
