REQUEST_APP_CLOSE = "request.app.close"
REQUEST_NOTIFICATION_SHOW = "request.notification.show"
REQUEST_PAGE_SHOW = "request.page.show"
REQUEST_TIMER_START = "request.timer.start"
REQUEST_TIMER_CANCEL = "request.timer.cancel"
REQUEST_LOG_TIME = "request.log.time"
REQUEST_PLUGINS_APPLY = "request.plugins.apply"
REQUEST_PLUGINS_RELOAD = "request.plugins.reload"

ACTION_LOG_DATA = "action.log.data"
ACTION_LOG_EVENT = "action.log.event"
ACTION_NOTIFICATION_SHOWN = "action.notification.shown"
ACTION_TIMER_COMPLETE = "action.timer.complete"
ACTION_STORAGE_CHANGED = "action.storage.changed"
ACTION_STORAGE_RESTORED = "action.storage.restored"
ACTION_PLUGINS_CHANGED = "action.plugins.changed"
